//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mascotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_mascotas()
        {
            this.tbl_venta = new HashSet<tbl_venta>();
        }
    
        public string id_m { get; set; }
        public string id_e { get; set; }
        public string id_r { get; set; }
        public string nombre_m { get; set; }
        public Nullable<int> edad_m { get; set; }
        public string sexo_m { get; set; }
        public string id_c { get; set; }
        public System.DateTime fechaNacimiento_m { get; set; }
    
        public virtual tbl_cliente tbl_cliente { get; set; }
        public virtual tbl_especie tbl_especie { get; set; }
        public virtual tbl_raza tbl_raza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_venta> tbl_venta { get; set; }
    }
}
