//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class veterinariaEntities1 : DbContext
    {
        public veterinariaEntities1()
            : base("name=veterinariaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_cliente> tbl_cliente { get; set; }
        public virtual DbSet<tbl_especie> tbl_especie { get; set; }
        public virtual DbSet<tbl_mascotas> tbl_mascotas { get; set; }
        public virtual DbSet<tbl_productos> tbl_productos { get; set; }
        public virtual DbSet<tbl_profesional> tbl_profesional { get; set; }
        public virtual DbSet<tbl_raza> tbl_raza { get; set; }
        public virtual DbSet<tbl_servicio> tbl_servicio { get; set; }
        public virtual DbSet<tbl_tipoProducto> tbl_tipoProducto { get; set; }
        public virtual DbSet<tbl_venta> tbl_venta { get; set; }
    
        public virtual int PA_deleteCliente(string id_c)
        {
            var id_cParameter = id_c != null ?
                new ObjectParameter("id_c", id_c) :
                new ObjectParameter("id_c", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteCliente", id_cParameter);
        }
    
        public virtual int PA_deleteEspecie(string id_e)
        {
            var id_eParameter = id_e != null ?
                new ObjectParameter("id_e", id_e) :
                new ObjectParameter("id_e", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteEspecie", id_eParameter);
        }
    
        public virtual int PA_deleteMascota(string id_m)
        {
            var id_mParameter = id_m != null ?
                new ObjectParameter("id_m", id_m) :
                new ObjectParameter("id_m", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteMascota", id_mParameter);
        }
    
        public virtual int PA_deleteProducto(string codigo_pd)
        {
            var codigo_pdParameter = codigo_pd != null ?
                new ObjectParameter("codigo_pd", codigo_pd) :
                new ObjectParameter("codigo_pd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteProducto", codigo_pdParameter);
        }
    
        public virtual int PA_deleteProfesional(string codigo_pf)
        {
            var codigo_pfParameter = codigo_pf != null ?
                new ObjectParameter("codigo_pf", codigo_pf) :
                new ObjectParameter("codigo_pf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteProfesional", codigo_pfParameter);
        }
    
        public virtual int PA_deleteRaza(string id_r)
        {
            var id_rParameter = id_r != null ?
                new ObjectParameter("id_r", id_r) :
                new ObjectParameter("id_r", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteRaza", id_rParameter);
        }
    
        public virtual int PA_deleteServicio(string codigo_s)
        {
            var codigo_sParameter = codigo_s != null ?
                new ObjectParameter("codigo_s", codigo_s) :
                new ObjectParameter("codigo_s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteServicio", codigo_sParameter);
        }
    
        public virtual int PA_deleteTipoProducto(string codigo_tp)
        {
            var codigo_tpParameter = codigo_tp != null ?
                new ObjectParameter("codigo_tp", codigo_tp) :
                new ObjectParameter("codigo_tp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteTipoProducto", codigo_tpParameter);
        }
    
        public virtual int PA_deleteVenta(string codigo_v)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteVenta", codigo_vParameter);
        }
    
        public virtual int PA_deleteVentaProducto(string codigo_v, string codigo_pd)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var codigo_pdParameter = codigo_pd != null ?
                new ObjectParameter("codigo_pd", codigo_pd) :
                new ObjectParameter("codigo_pd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteVentaProducto", codigo_vParameter, codigo_pdParameter);
        }
    
        public virtual int PA_deleteVentaServicio(string codigo_v, string codigo_s)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var codigo_sParameter = codigo_s != null ?
                new ObjectParameter("codigo_s", codigo_s) :
                new ObjectParameter("codigo_s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_deleteVentaServicio", codigo_vParameter, codigo_sParameter);
        }
    
        public virtual int PA_insertCliente(string id_c, string nombre_c, string apellido_c, Nullable<System.DateTime> fechaNacimiento_c, Nullable<int> edad_c)
        {
            var id_cParameter = id_c != null ?
                new ObjectParameter("id_c", id_c) :
                new ObjectParameter("id_c", typeof(string));
    
            var nombre_cParameter = nombre_c != null ?
                new ObjectParameter("nombre_c", nombre_c) :
                new ObjectParameter("nombre_c", typeof(string));
    
            var apellido_cParameter = apellido_c != null ?
                new ObjectParameter("apellido_c", apellido_c) :
                new ObjectParameter("apellido_c", typeof(string));
    
            var fechaNacimiento_cParameter = fechaNacimiento_c.HasValue ?
                new ObjectParameter("fechaNacimiento_c", fechaNacimiento_c) :
                new ObjectParameter("fechaNacimiento_c", typeof(System.DateTime));
    
            var edad_cParameter = edad_c.HasValue ?
                new ObjectParameter("edad_c", edad_c) :
                new ObjectParameter("edad_c", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertCliente", id_cParameter, nombre_cParameter, apellido_cParameter, fechaNacimiento_cParameter, edad_cParameter);
        }
    
        public virtual int PA_insertEspecie(string id_e, string nombre_e)
        {
            var id_eParameter = id_e != null ?
                new ObjectParameter("id_e", id_e) :
                new ObjectParameter("id_e", typeof(string));
    
            var nombre_eParameter = nombre_e != null ?
                new ObjectParameter("nombre_e", nombre_e) :
                new ObjectParameter("nombre_e", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertEspecie", id_eParameter, nombre_eParameter);
        }
    
        public virtual int PA_insertMascota(string id_m, string id_e, string id_r, string nombre_m, Nullable<int> edad_m, string sexo_m, string id_c, Nullable<System.DateTime> fechaNacimiento_m)
        {
            var id_mParameter = id_m != null ?
                new ObjectParameter("id_m", id_m) :
                new ObjectParameter("id_m", typeof(string));
    
            var id_eParameter = id_e != null ?
                new ObjectParameter("id_e", id_e) :
                new ObjectParameter("id_e", typeof(string));
    
            var id_rParameter = id_r != null ?
                new ObjectParameter("id_r", id_r) :
                new ObjectParameter("id_r", typeof(string));
    
            var nombre_mParameter = nombre_m != null ?
                new ObjectParameter("nombre_m", nombre_m) :
                new ObjectParameter("nombre_m", typeof(string));
    
            var edad_mParameter = edad_m.HasValue ?
                new ObjectParameter("edad_m", edad_m) :
                new ObjectParameter("edad_m", typeof(int));
    
            var sexo_mParameter = sexo_m != null ?
                new ObjectParameter("sexo_m", sexo_m) :
                new ObjectParameter("sexo_m", typeof(string));
    
            var id_cParameter = id_c != null ?
                new ObjectParameter("id_c", id_c) :
                new ObjectParameter("id_c", typeof(string));
    
            var fechaNacimiento_mParameter = fechaNacimiento_m.HasValue ?
                new ObjectParameter("fechaNacimiento_m", fechaNacimiento_m) :
                new ObjectParameter("fechaNacimiento_m", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertMascota", id_mParameter, id_eParameter, id_rParameter, nombre_mParameter, edad_mParameter, sexo_mParameter, id_cParameter, fechaNacimiento_mParameter);
        }
    
        public virtual int PA_insertProducto(string codigo_pd, string nombre_pd, string codigo_tp, Nullable<double> precio_pd)
        {
            var codigo_pdParameter = codigo_pd != null ?
                new ObjectParameter("codigo_pd", codigo_pd) :
                new ObjectParameter("codigo_pd", typeof(string));
    
            var nombre_pdParameter = nombre_pd != null ?
                new ObjectParameter("nombre_pd", nombre_pd) :
                new ObjectParameter("nombre_pd", typeof(string));
    
            var codigo_tpParameter = codigo_tp != null ?
                new ObjectParameter("codigo_tp", codigo_tp) :
                new ObjectParameter("codigo_tp", typeof(string));
    
            var precio_pdParameter = precio_pd.HasValue ?
                new ObjectParameter("precio_pd", precio_pd) :
                new ObjectParameter("precio_pd", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertProducto", codigo_pdParameter, nombre_pdParameter, codigo_tpParameter, precio_pdParameter);
        }
    
        public virtual int PA_insertProfesional(string codigo_pf, string nombre_pf, string apellido_pf, string telefono_pf, string celular_pf)
        {
            var codigo_pfParameter = codigo_pf != null ?
                new ObjectParameter("codigo_pf", codigo_pf) :
                new ObjectParameter("codigo_pf", typeof(string));
    
            var nombre_pfParameter = nombre_pf != null ?
                new ObjectParameter("nombre_pf", nombre_pf) :
                new ObjectParameter("nombre_pf", typeof(string));
    
            var apellido_pfParameter = apellido_pf != null ?
                new ObjectParameter("apellido_pf", apellido_pf) :
                new ObjectParameter("apellido_pf", typeof(string));
    
            var telefono_pfParameter = telefono_pf != null ?
                new ObjectParameter("telefono_pf", telefono_pf) :
                new ObjectParameter("telefono_pf", typeof(string));
    
            var celular_pfParameter = celular_pf != null ?
                new ObjectParameter("celular_pf", celular_pf) :
                new ObjectParameter("celular_pf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertProfesional", codigo_pfParameter, nombre_pfParameter, apellido_pfParameter, telefono_pfParameter, celular_pfParameter);
        }
    
        public virtual int PA_insertRaza(string id_r, string nombre_r)
        {
            var id_rParameter = id_r != null ?
                new ObjectParameter("id_r", id_r) :
                new ObjectParameter("id_r", typeof(string));
    
            var nombre_rParameter = nombre_r != null ?
                new ObjectParameter("nombre_r", nombre_r) :
                new ObjectParameter("nombre_r", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertRaza", id_rParameter, nombre_rParameter);
        }
    
        public virtual int PA_insertServicio(string codigo_s, string nombre_s, Nullable<double> precio_s)
        {
            var codigo_sParameter = codigo_s != null ?
                new ObjectParameter("codigo_s", codigo_s) :
                new ObjectParameter("codigo_s", typeof(string));
    
            var nombre_sParameter = nombre_s != null ?
                new ObjectParameter("nombre_s", nombre_s) :
                new ObjectParameter("nombre_s", typeof(string));
    
            var precio_sParameter = precio_s.HasValue ?
                new ObjectParameter("precio_s", precio_s) :
                new ObjectParameter("precio_s", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertServicio", codigo_sParameter, nombre_sParameter, precio_sParameter);
        }
    
        public virtual int PA_insertTipoProducto(string codigo_tp, string nombre_tp)
        {
            var codigo_tpParameter = codigo_tp != null ?
                new ObjectParameter("codigo_tp", codigo_tp) :
                new ObjectParameter("codigo_tp", typeof(string));
    
            var nombre_tpParameter = nombre_tp != null ?
                new ObjectParameter("nombre_tp", nombre_tp) :
                new ObjectParameter("nombre_tp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertTipoProducto", codigo_tpParameter, nombre_tpParameter);
        }
    
        public virtual int PA_insertVenta(string codigo_v, Nullable<System.DateTime> fecha_v, string id_m, string codigo_pf)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var fecha_vParameter = fecha_v.HasValue ?
                new ObjectParameter("fecha_v", fecha_v) :
                new ObjectParameter("fecha_v", typeof(System.DateTime));
    
            var id_mParameter = id_m != null ?
                new ObjectParameter("id_m", id_m) :
                new ObjectParameter("id_m", typeof(string));
    
            var codigo_pfParameter = codigo_pf != null ?
                new ObjectParameter("codigo_pf", codigo_pf) :
                new ObjectParameter("codigo_pf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertVenta", codigo_vParameter, fecha_vParameter, id_mParameter, codigo_pfParameter);
        }
    
        public virtual int PA_insertVentaProducto(string codigo_v, string codigo_pd)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var codigo_pdParameter = codigo_pd != null ?
                new ObjectParameter("codigo_pd", codigo_pd) :
                new ObjectParameter("codigo_pd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertVentaProducto", codigo_vParameter, codigo_pdParameter);
        }
    
        public virtual int PA_insertVentaServicio(string codigo_v, string codigo_s)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var codigo_sParameter = codigo_s != null ?
                new ObjectParameter("codigo_s", codigo_s) :
                new ObjectParameter("codigo_s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insertVentaServicio", codigo_vParameter, codigo_sParameter);
        }
    
        public virtual ObjectResult<PA_selectAllCliente_Result> PA_selectAllCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllCliente_Result>("PA_selectAllCliente");
        }
    
        public virtual ObjectResult<PA_selectAllEspecie_Result> PA_selectAllEspecie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllEspecie_Result>("PA_selectAllEspecie");
        }
    
        public virtual ObjectResult<PA_selectAllMascota_Result> PA_selectAllMascota()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllMascota_Result>("PA_selectAllMascota");
        }
    
        public virtual ObjectResult<PA_selectAllProducto_Result> PA_selectAllProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllProducto_Result>("PA_selectAllProducto");
        }
    
        public virtual ObjectResult<PA_selectAllProfesional_Result> PA_selectAllProfesional()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllProfesional_Result>("PA_selectAllProfesional");
        }
    
        public virtual ObjectResult<PA_selectAllRaza_Result> PA_selectAllRaza()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllRaza_Result>("PA_selectAllRaza");
        }
    
        public virtual ObjectResult<PA_selectAllServicio_Result> PA_selectAllServicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllServicio_Result>("PA_selectAllServicio");
        }
    
        public virtual ObjectResult<PA_selectAllTipoProducto_Result> PA_selectAllTipoProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllTipoProducto_Result>("PA_selectAllTipoProducto");
        }
    
        public virtual ObjectResult<PA_selectAllVenta_Result> PA_selectAllVenta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllVenta_Result>("PA_selectAllVenta");
        }
    
        public virtual ObjectResult<PA_selectAllVentaProducto_Result> PA_selectAllVentaProducto(string codigo_v)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllVentaProducto_Result>("PA_selectAllVentaProducto", codigo_vParameter);
        }
    
        public virtual ObjectResult<PA_selectAllVentaServicio_Result> PA_selectAllVentaServicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectAllVentaServicio_Result>("PA_selectAllVentaServicio");
        }
    
        public virtual ObjectResult<PA_selectOneCliente_Result> PA_selectOneCliente(string id_c)
        {
            var id_cParameter = id_c != null ?
                new ObjectParameter("id_c", id_c) :
                new ObjectParameter("id_c", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneCliente_Result>("PA_selectOneCliente", id_cParameter);
        }
    
        public virtual ObjectResult<PA_selectOneEspecie_Result> PA_selectOneEspecie(string id_e)
        {
            var id_eParameter = id_e != null ?
                new ObjectParameter("id_e", id_e) :
                new ObjectParameter("id_e", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneEspecie_Result>("PA_selectOneEspecie", id_eParameter);
        }
    
        public virtual ObjectResult<PA_selectOneMascota_Result> PA_selectOneMascota(string id_m)
        {
            var id_mParameter = id_m != null ?
                new ObjectParameter("id_m", id_m) :
                new ObjectParameter("id_m", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneMascota_Result>("PA_selectOneMascota", id_mParameter);
        }
    
        public virtual ObjectResult<PA_selectOneProducto_Result> PA_selectOneProducto(string codigo_pd)
        {
            var codigo_pdParameter = codigo_pd != null ?
                new ObjectParameter("codigo_pd", codigo_pd) :
                new ObjectParameter("codigo_pd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneProducto_Result>("PA_selectOneProducto", codigo_pdParameter);
        }
    
        public virtual ObjectResult<PA_selectOneProfesional_Result> PA_selectOneProfesional(string codigo_pf)
        {
            var codigo_pfParameter = codigo_pf != null ?
                new ObjectParameter("codigo_pf", codigo_pf) :
                new ObjectParameter("codigo_pf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneProfesional_Result>("PA_selectOneProfesional", codigo_pfParameter);
        }
    
        public virtual ObjectResult<PA_selectOneRaza_Result> PA_selectOneRaza(string id_r)
        {
            var id_rParameter = id_r != null ?
                new ObjectParameter("id_r", id_r) :
                new ObjectParameter("id_r", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneRaza_Result>("PA_selectOneRaza", id_rParameter);
        }
    
        public virtual ObjectResult<PA_selectOneServicio_Result> PA_selectOneServicio(string codigo_s)
        {
            var codigo_sParameter = codigo_s != null ?
                new ObjectParameter("codigo_s", codigo_s) :
                new ObjectParameter("codigo_s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneServicio_Result>("PA_selectOneServicio", codigo_sParameter);
        }
    
        public virtual ObjectResult<PA_selectOneTipoProducto_Result> PA_selectOneTipoProducto(string codigo_tp)
        {
            var codigo_tpParameter = codigo_tp != null ?
                new ObjectParameter("codigo_tp", codigo_tp) :
                new ObjectParameter("codigo_tp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneTipoProducto_Result>("PA_selectOneTipoProducto", codigo_tpParameter);
        }
    
        public virtual ObjectResult<PA_selectOneVenta_Result> PA_selectOneVenta(string codigo_v)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneVenta_Result>("PA_selectOneVenta", codigo_vParameter);
        }
    
        public virtual ObjectResult<PA_selectOneVentaProducto_Result> PA_selectOneVentaProducto(string codigo_v)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneVentaProducto_Result>("PA_selectOneVentaProducto", codigo_vParameter);
        }
    
        public virtual ObjectResult<PA_selectOneVentaServicio_Result> PA_selectOneVentaServicio(string codigo_v)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_selectOneVentaServicio_Result>("PA_selectOneVentaServicio", codigo_vParameter);
        }
    
        public virtual int PA_updateCliente(string id_c, string nombre_c, string apellido_c, Nullable<System.DateTime> fechaNacimiento_c, Nullable<int> edad_c)
        {
            var id_cParameter = id_c != null ?
                new ObjectParameter("id_c", id_c) :
                new ObjectParameter("id_c", typeof(string));
    
            var nombre_cParameter = nombre_c != null ?
                new ObjectParameter("nombre_c", nombre_c) :
                new ObjectParameter("nombre_c", typeof(string));
    
            var apellido_cParameter = apellido_c != null ?
                new ObjectParameter("apellido_c", apellido_c) :
                new ObjectParameter("apellido_c", typeof(string));
    
            var fechaNacimiento_cParameter = fechaNacimiento_c.HasValue ?
                new ObjectParameter("fechaNacimiento_c", fechaNacimiento_c) :
                new ObjectParameter("fechaNacimiento_c", typeof(System.DateTime));
    
            var edad_cParameter = edad_c.HasValue ?
                new ObjectParameter("edad_c", edad_c) :
                new ObjectParameter("edad_c", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateCliente", id_cParameter, nombre_cParameter, apellido_cParameter, fechaNacimiento_cParameter, edad_cParameter);
        }
    
        public virtual int PA_updateEspecie(string id_e, string nombre_e)
        {
            var id_eParameter = id_e != null ?
                new ObjectParameter("id_e", id_e) :
                new ObjectParameter("id_e", typeof(string));
    
            var nombre_eParameter = nombre_e != null ?
                new ObjectParameter("nombre_e", nombre_e) :
                new ObjectParameter("nombre_e", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateEspecie", id_eParameter, nombre_eParameter);
        }
    
        public virtual int PA_updateMascota(string id_m, string id_e, string id_r, string nombre_m, Nullable<int> edad_m, string sexo_m, string id_c, Nullable<System.DateTime> fechaNacimiento_m)
        {
            var id_mParameter = id_m != null ?
                new ObjectParameter("id_m", id_m) :
                new ObjectParameter("id_m", typeof(string));
    
            var id_eParameter = id_e != null ?
                new ObjectParameter("id_e", id_e) :
                new ObjectParameter("id_e", typeof(string));
    
            var id_rParameter = id_r != null ?
                new ObjectParameter("id_r", id_r) :
                new ObjectParameter("id_r", typeof(string));
    
            var nombre_mParameter = nombre_m != null ?
                new ObjectParameter("nombre_m", nombre_m) :
                new ObjectParameter("nombre_m", typeof(string));
    
            var edad_mParameter = edad_m.HasValue ?
                new ObjectParameter("edad_m", edad_m) :
                new ObjectParameter("edad_m", typeof(int));
    
            var sexo_mParameter = sexo_m != null ?
                new ObjectParameter("sexo_m", sexo_m) :
                new ObjectParameter("sexo_m", typeof(string));
    
            var id_cParameter = id_c != null ?
                new ObjectParameter("id_c", id_c) :
                new ObjectParameter("id_c", typeof(string));
    
            var fechaNacimiento_mParameter = fechaNacimiento_m.HasValue ?
                new ObjectParameter("fechaNacimiento_m", fechaNacimiento_m) :
                new ObjectParameter("fechaNacimiento_m", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateMascota", id_mParameter, id_eParameter, id_rParameter, nombre_mParameter, edad_mParameter, sexo_mParameter, id_cParameter, fechaNacimiento_mParameter);
        }
    
        public virtual int PA_updateProducto(string codigo_pd, string nombre_pd, string codigo_tp, Nullable<double> precio_pd)
        {
            var codigo_pdParameter = codigo_pd != null ?
                new ObjectParameter("codigo_pd", codigo_pd) :
                new ObjectParameter("codigo_pd", typeof(string));
    
            var nombre_pdParameter = nombre_pd != null ?
                new ObjectParameter("nombre_pd", nombre_pd) :
                new ObjectParameter("nombre_pd", typeof(string));
    
            var codigo_tpParameter = codigo_tp != null ?
                new ObjectParameter("codigo_tp", codigo_tp) :
                new ObjectParameter("codigo_tp", typeof(string));
    
            var precio_pdParameter = precio_pd.HasValue ?
                new ObjectParameter("precio_pd", precio_pd) :
                new ObjectParameter("precio_pd", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateProducto", codigo_pdParameter, nombre_pdParameter, codigo_tpParameter, precio_pdParameter);
        }
    
        public virtual int PA_updateProfesional(string codigo_pf, string nombre_pf, string apellido_pf, string telefono_pf, string celular_pf)
        {
            var codigo_pfParameter = codigo_pf != null ?
                new ObjectParameter("codigo_pf", codigo_pf) :
                new ObjectParameter("codigo_pf", typeof(string));
    
            var nombre_pfParameter = nombre_pf != null ?
                new ObjectParameter("nombre_pf", nombre_pf) :
                new ObjectParameter("nombre_pf", typeof(string));
    
            var apellido_pfParameter = apellido_pf != null ?
                new ObjectParameter("apellido_pf", apellido_pf) :
                new ObjectParameter("apellido_pf", typeof(string));
    
            var telefono_pfParameter = telefono_pf != null ?
                new ObjectParameter("telefono_pf", telefono_pf) :
                new ObjectParameter("telefono_pf", typeof(string));
    
            var celular_pfParameter = celular_pf != null ?
                new ObjectParameter("celular_pf", celular_pf) :
                new ObjectParameter("celular_pf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateProfesional", codigo_pfParameter, nombre_pfParameter, apellido_pfParameter, telefono_pfParameter, celular_pfParameter);
        }
    
        public virtual int PA_updateRaza(string id_r, string nombre_r)
        {
            var id_rParameter = id_r != null ?
                new ObjectParameter("id_r", id_r) :
                new ObjectParameter("id_r", typeof(string));
    
            var nombre_rParameter = nombre_r != null ?
                new ObjectParameter("nombre_r", nombre_r) :
                new ObjectParameter("nombre_r", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateRaza", id_rParameter, nombre_rParameter);
        }
    
        public virtual int PA_updateServicio(string codigo_s, string nombre_s, Nullable<double> precio_s)
        {
            var codigo_sParameter = codigo_s != null ?
                new ObjectParameter("codigo_s", codigo_s) :
                new ObjectParameter("codigo_s", typeof(string));
    
            var nombre_sParameter = nombre_s != null ?
                new ObjectParameter("nombre_s", nombre_s) :
                new ObjectParameter("nombre_s", typeof(string));
    
            var precio_sParameter = precio_s.HasValue ?
                new ObjectParameter("precio_s", precio_s) :
                new ObjectParameter("precio_s", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateServicio", codigo_sParameter, nombre_sParameter, precio_sParameter);
        }
    
        public virtual int PA_updateTipoProducto(string codigo_tp, string nombre_tp)
        {
            var codigo_tpParameter = codigo_tp != null ?
                new ObjectParameter("codigo_tp", codigo_tp) :
                new ObjectParameter("codigo_tp", typeof(string));
    
            var nombre_tpParameter = nombre_tp != null ?
                new ObjectParameter("nombre_tp", nombre_tp) :
                new ObjectParameter("nombre_tp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateTipoProducto", codigo_tpParameter, nombre_tpParameter);
        }
    
        public virtual int PA_updateVenta(string codigo_v, Nullable<System.DateTime> fecha_v, string id_m, string codigo_pf)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var fecha_vParameter = fecha_v.HasValue ?
                new ObjectParameter("fecha_v", fecha_v) :
                new ObjectParameter("fecha_v", typeof(System.DateTime));
    
            var id_mParameter = id_m != null ?
                new ObjectParameter("id_m", id_m) :
                new ObjectParameter("id_m", typeof(string));
    
            var codigo_pfParameter = codigo_pf != null ?
                new ObjectParameter("codigo_pf", codigo_pf) :
                new ObjectParameter("codigo_pf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateVenta", codigo_vParameter, fecha_vParameter, id_mParameter, codigo_pfParameter);
        }
    
        public virtual int PA_updateVentaProducto(string codigo_v, string codigo_pd)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var codigo_pdParameter = codigo_pd != null ?
                new ObjectParameter("codigo_pd", codigo_pd) :
                new ObjectParameter("codigo_pd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateVentaProducto", codigo_vParameter, codigo_pdParameter);
        }
    
        public virtual int PA_updateVentaServicio(string codigo_v, string codigo_s)
        {
            var codigo_vParameter = codigo_v != null ?
                new ObjectParameter("codigo_v", codigo_v) :
                new ObjectParameter("codigo_v", typeof(string));
    
            var codigo_sParameter = codigo_s != null ?
                new ObjectParameter("codigo_s", codigo_s) :
                new ObjectParameter("codigo_s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_updateVentaServicio", codigo_vParameter, codigo_sParameter);
        }
    }
}
